/**
 * Firestore Security Rules Test Suite — Verifies the "Dirty Dozen" Payloads
 */
export const DIRTY_DOZEN_TEST_CASES = [
  {
    id: 1,
    name: 'Privilege Escalation on Create',
    path: '/profiles/user_123',
    operation: 'create',
    auth: { uid: 'user_123', email: 'regular@gmail.com', email_verified: true },
    payload: {
      uid: 'user_123',
      email: 'regular@gmail.com',
      fullName: 'Regular User',
      avatarUrl: '',
      phone: '',
      role: 'admin',
      createdAt: 'SERVER_TIMESTAMP',
      lastLoginAt: 'SERVER_TIMESTAMP',
    },
    expected: 'PERMISSION_DENIED',
  },
  {
    id: 2,
    name: 'Self-Role Promotion on Update',
    path: '/profiles/user_123',
    operation: 'update',
    auth: { uid: 'user_123', email: 'regular@gmail.com', email_verified: true },
    payload: { role: 'admin' },
    expected: 'PERMISSION_DENIED',
  },
  {
    id: 3,
    name: 'Shadow Field Injection',
    path: '/profiles/user_123',
    operation: 'create',
    auth: { uid: 'user_123', email: 'regular@gmail.com', email_verified: true },
    payload: {
      uid: 'user_123',
      email: 'regular@gmail.com',
      fullName: 'Regular User',
      avatarUrl: '',
      phone: '',
      role: 'user',
      isSuperUser: true,
      createdAt: 'SERVER_TIMESTAMP',
      lastLoginAt: 'SERVER_TIMESTAMP',
    },
    expected: 'PERMISSION_DENIED',
  },
  {
    id: 4,
    name: 'PII Horizontal Scraping',
    path: '/profiles/user_123',
    operation: 'get',
    auth: { uid: 'user_456', email: 'other@gmail.com', email_verified: true },
    expected: 'PERMISSION_DENIED',
  },
  {
    id: 5,
    name: 'Unverified Admin Email Spoof',
    path: '/profiles/user_123',
    operation: 'get',
    auth: { uid: 'spoof_uid', email: 'sidhantmaurya140@gmail.com', email_verified: false },
    expected: 'PERMISSION_DENIED',
  },
  {
    id: 6,
    name: 'ID Poisoning Attack',
    path: '/contact_messages/invalid$id!@#',
    operation: 'create',
    auth: null,
    payload: {},
    expected: 'PERMISSION_DENIED',
  },
  {
    id: 7,
    name: 'Contact Message Pre-Marked Replied',
    path: '/contact_messages/msg_1',
    operation: 'create',
    auth: null,
    payload: {
      userId: 'guest',
      fullName: 'Visitor Name',
      email: 'visitor@example.com',
      phone: '',
      reason: 'General Inquiry',
      message: 'Valid length inquiry message text.',
      status: 'replied',
      adminNotes: 'Hacked notes',
      createdAt: 'SERVER_TIMESTAMP',
      updatedAt: 'SERVER_TIMESTAMP',
      notifiedAt: '',
      notificationError: '',
    },
    expected: 'PERMISSION_DENIED',
  },
  {
    id: 8,
    name: 'Contact Message Identity Spoofing',
    path: '/contact_messages/msg_1',
    operation: 'create',
    auth: { uid: 'user_123', email: 'regular@gmail.com', email_verified: true },
    payload: {
      userId: 'user_999',
      fullName: 'Spoofed Sender',
      email: 'regular@gmail.com',
      phone: '',
      reason: 'General Inquiry',
      message: 'Valid length inquiry message text.',
      status: 'new',
      adminNotes: '',
      createdAt: 'SERVER_TIMESTAMP',
      updatedAt: 'SERVER_TIMESTAMP',
      notifiedAt: '',
      notificationError: '',
    },
    expected: 'PERMISSION_DENIED',
  },
  {
    id: 9,
    name: 'Denial of Wallet Oversized Message',
    path: '/contact_messages/msg_1',
    operation: 'create',
    auth: null,
    payload: {
      userId: 'guest',
      fullName: 'Visitor Name',
      email: 'visitor@example.com',
      phone: '',
      reason: 'General Inquiry',
      message: 'A'.repeat(6000),
      status: 'new',
      adminNotes: '',
      createdAt: 'SERVER_TIMESTAMP',
      updatedAt: 'SERVER_TIMESTAMP',
      notifiedAt: '',
      notificationError: '',
    },
    expected: 'PERMISSION_DENIED',
  },
  {
    id: 10,
    name: 'Anonymous Message Scraping',
    path: '/contact_messages/msg_1',
    operation: 'get',
    auth: null,
    expected: 'PERMISSION_DENIED',
  },
  {
    id: 11,
    name: 'Forged Client Timestamp on Subscriber',
    path: '/newsletter_subscribers/sub_1',
    operation: 'create',
    auth: null,
    payload: {
      email: 'sub@example.com',
      createdAt: '2020-01-01T00:00:00Z',
    },
    expected: 'PERMISSION_DENIED',
  },
  {
    id: 12,
    name: 'Immutable Field Mutation on Profile',
    path: '/profiles/user_123',
    operation: 'update',
    auth: { uid: 'user_123', email: 'regular@gmail.com', email_verified: true },
    payload: {
      uid: 'different_uid',
    },
    expected: 'PERMISSION_DENIED',
  },
];
